import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('grAPCg8AAAgsADAgkAeAr9AoOCxo6AMAgmCMCiKAgmEFAhDEEBDABABAGAeBBAAAekLHDTBhZAdYgnFnUAIAg1HhuAlPEBeJPj_iCVg-DfBkBgvUBF4M_bAs3AACijAPCg8AAAiCAFD4NbTAYAeAYAeAYAeAYAeAYAxcrB');
